export enum DemandeTypeEnum {
  FORMULAIRE_SIMPLIFIE = 'FORMULAIRE_SIMPLIFIE',
  LIEN_EXTERNE = 'LIEN_EXTERNE',
  DEMANDE_HORS_TRAVAUX = 'DEMANDE_HORS_TRAVAUX',
  DEMANDE_TRAVAUX = 'DEMANDE_TRAVAUX'
}